---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server
  namespace: openvpn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openvpn-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openvpn-server
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Chicago
        - name: INTERFACE
          value: eth0
        image: linuxserver/openvpn-as
        imagePullPolicy: IfNotPresent
        name: openvpn-server
        ports:
        - containerPort: 1194
          name: openvpn-server
          protocol: UDP
        - containerPort: 943
          name: port1
          protocol: TCP
        - containerPort: 9443
          name: port2
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 800Mi
          requests:
            cpu: "1"
            memory: 800Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/openvpn
          name: openvpn-data
        - mountPath: /config
          name: configs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: openvpn-data
      - name: configs
        persistentVolumeClaim:
          claimName: openvpn-server-pv-claim
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-generic-storage-class
parameters:
  type: gp2
  zone: us-east-1a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server-pv-claim
  namespace: openvpn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws-generic-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server-data-pv-claim
  namespace: openvpn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: aws-generic-storage-class
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ambassador-service
  name: openvpn-gui-service
  namespace: openvpn
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 943
  selector:
    app: openvpn-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ambassador-service
  name: openvpn-server-service
  namespace: openvpn
spec:
  ports:
  - name: server
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: openvpn-server
  sessionAffinity: None
  type: ClusterIP