apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: default
spec:
  chart:
    spec:
      chart: stable/openvpn
      sourceRef:
        kind: HelmRepository
        name: openvpn
      version: '0.18.0'
  interval: 30m0s